### ISSUE TITLE
Dimension mismatch

### ISSUE THREAD

**Issue by alien19** [yuxiao17/LDS-Net#2]
Hello @yuxiao17 
I have downloaded the provided checkpoints and ran the test script but got the following error:
```
 Error(s) in loading state_dict for RestoreNet_Unet:
        size mismatch for conv1_1.conv_relu.0.weight: copying a param with shape torch.Size([32, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
```

**Comment by yuxiao17** [comment]
I'm sorry that the code version given earlier is the code used in the ablation experiment. The code for models.py and test.py has been updated. You can try to run them again.
Specifically, we changed the line 251,296 and 298 in models.py and the line 41 in test.py.
Thank you for your attention. If you have any questions, feel free to contact us. I am the author of this article. My common email is 3298729503@qq.com. You can also send pictures or other contents to my email for convenient communication.

**Comment by alien19** [comment]
Thank you @yuxiao17!

**Comment by alien19** [comment]
Thanks @yuxiao17 !
